config:
  backup: false
  dotpath: home
  longkey: true
  showdiff: true
dotfiles:
  d_bin:
    src: bin
    dst: ~/bin
    chmod: "755"
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  d_config_aerc:
    src: config/aerc
    dst: ~/.config/aerc
    cmpignore:
      - accounts.conf
    instignore:
      - accounts.conf
    upignore:
      - accounts.conf
  d_config_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_config_environment.d:
    src: config/environment.d
    dst: ~/.config/environment.d
  d_config_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
  d_config_gammastep:
    src: config/gammastep
    dst: ~/.config/gammastep
  d_config_git:
    src: config/git
    dst: ~/.config/git
  d_config_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_config_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
  d_config_i3status-rust:
    src: config/i3status-rust
    dst: ~/.config/i3status-rust
  d_config_kanshi:
    src: config/kanshi
    dst: ~/.config/kanshi
  d_config_mako:
    src: config/mako
    dst: ~/.config/mako
  f_config_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_config_rbw:
    src: config/rbw
    dst: ~/.config/rbw
  d_config_systemd:
    src: config/systemd
    dst: ~/.config/systemd
    cmpignore:
      - "*.wants"
    upignore:
      - "*.wants"
  d_config_stylua:
    src: config/stylua
    dst: ~/.config/stylua
  d_config_sway:
    src: config/sway
    dst: ~/.config/sway
  d_config_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  f_config_wallpaper_arch-linux-dark.png:
    src: config/wallpaper/arch-linux-dark.png
    dst: ~/.config/wallpaper/arch-linux-dark.png
  d_config_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_config_zsh:
    dst: ~/.config/zsh
    src: config/zsh
variables:
  git:
    email: mail@berrio.dev
    signingkey: A9FDFA72
    gpgsign: true
profiles:
  desktop:
    dotfiles:
      - f_gtkrc-2.0
      - d_config_alacritty
      - d_config_environment.d
      - d_config_fuzzel
      - d_config_gammastep
      - d_config_gtk-3.0
      - d_config_gtk-4.0
      - f_config_mimeapps.list
      - d_config_rbw
      - d_config_systemd
      - f_config_wallpaper_arch-linux-dark.png
      - d_config_zathura
  mail:
    dotfiles:
      - d_config_aerc
  sway:
    dotfiles:
      - d_config_git
      - d_config_i3status-rust
      - d_config_kanshi
      - d_config_mako
      - d_config_sway
  terminal:
    dotfiles:
      - d_bin
      - f_zshenv
      - f_zshrc
      - d_config_nvim
      - d_config_stylua
      - d_config_tmux
      - d_config_zsh
  willow:
    include:
      - desktop
      - mail
      - sway
      - terminal
  server:
    include:
      - terminal
    variables:
      git:
        email: "{{@@ env['GIT_EMAIL'] @@}}"
        gpgsign: false
