config:
  backup: false
  banner: true
  create: true
  dotpath: root
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/sdotdrop
dotfiles:
  f_etc_wsl.conf:
    src: etc/wsl.conf
    dst: /etc/wsl.conf
  f_etc_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_etc_welcomemessage.conf:
    src: etc/welcomemessage.conf
    dst: /etc/welcomemessage.conf
  f_etc_mkinitcpio.conf:
    src: etc/mkinitcpio.conf
    dst: /etc/mkinitcpio.conf
  f_etc_issue:
    src: etc/issue
    dst: /etc/issue
  d_etc_udev_rules.d:
    src: etc/udev/rules.d
    dst: /etc/udev/rules.d
  f_50-backup-boot.hook:
    src: usr/share/libalpm/hooks/50-backup-boot.hook
    dst: /usr/share/libalpm/hooks/50-backup-boot.hook
  f_50-snapshot-system.hook:
    src: usr/share/libalpm/hooks/50-snapshot-system.hook
    dst: /usr/share/libalpm/hooks/50-snapshot-system.hook
  f_99-newkernel.hook:
    src: usr/share/libalpm/hooks/99-newkernel.hook
    dst: /usr/share/libalpm/hooks/99-newkernel.hook
  f_snapshot-system:
    src: usr/share/libalpm/scripts/snapshot-system
    dst: /usr/share/libalpm/scripts/snapshot-system
  f_newkernel:
    src: usr/share/libalpm/scripts/newkernel
    dst: /usr/share/libalpm/scripts/newkernel
profiles:
  NB-MIB:
    dotfiles:
    - f_etc_wsl.conf
    - f_etc_pacman.conf
  arch-xps:
    dotfiles:
    - f_etc_pacman.conf
    - f_etc_welcomemessage.conf
    - f_etc_mkinitcpio.conf
    - f_etc_issue
    - d_etc_udev_rules.d
    - f_50-backup-boot.hook
    - f_50-snapshot-system.hook
    - f_99-newkernel.hook
    - f_snapshot-system
    - f_newkernel
