config:
  backup: false
  dotpath: home
  longkey: true
  showdiff: true
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  d_config_aerc:
    src: config/aerc
    dst: ~/.config/aerc
    cmpignore:
    - accounts.conf
    instignore:
    - accounts.conf
    upignore:
    - accounts.conf
  d_config_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
  d_config_git:
    src: config/git
    dst: ~/.config/git
  d_config_i3status-rust:
    src: config/i3status-rust
    dst: ~/.config/i3status-rust
  d_config_kanshi:
    src: config/kanshi
    dst: ~/.config/kanshi
  d_config_mako:
    src: config/mako
    dst: ~/.config/mako
  d_config_stylua:
    src: config/stylua
    dst: ~/.config/stylua
  d_config_sway:
    src: config/sway
    dst: ~/.config/sway
  d_config_zsh:
    dst: ~/.config/zsh
    src: config/zsh
variables:
  git:
    email: mail@berrio.dev
    signingkey: A9FDFA72
    gpgsign: true
profiles:
  desktop:
    dotfiles:
    - d_config_fuzzel
  mail:
    dotfiles:
    - d_config_aerc
  sway:
    dotfiles:
    - d_config_git
    - d_config_i3status-rust
    - d_config_kanshi
    - d_config_mako
    - d_config_sway
  terminal:
    dotfiles:
    - d_bin
    - f_zshrc
    - d_config_stylua
    - d_config_zsh

  willow:
    include:
    - desktop
    - mail
    - sway
    - terminal
