config:
  backup: false
  dotpath: home
  longkey: true
  showdiff: true
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  d_config_zsh:
    dst: ~/.config/zsh
    src: config/zsh
  d_config_aerc:
    src: config/aerc
    dst: ~/.config/aerc
    cmpignore:
    - accounts.conf
    instignore:
    - accounts.conf
    upignore:
    - accounts.conf
  d_config_mako:
    src: config/mako
    dst: ~/.config/mako
  d_config_sway:
    src: config/sway
    dst: ~/.config/sway
  d_config_kanshi:
    src: config/kanshi
    dst: ~/.config/kanshi
  d_config_fuzzel:
    src: config/fuzzel
    dst: ~/.config/fuzzel
variables:
  git:
    email: mail@berrio.dev
profiles:
  desktop:
    dotfiles:
    - d_config_fuzzel
  mail:
    dotfiles:
    - d_config_aerc
  sway:
    dotfiles:
    - d_config_kanshi
    - d_config_mako
    - d_config_sway
  terminal:
    dotfiles:
    - d_bin
    - f_zshrc
    - d_config_zsh

  willow:
    include:
    - desktop
    - mail
    - sway
    - terminal
