actions:
  vim-plug: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
config:
  backup: false
  banner: true
  cmpignore:
  - session.vim
  - '*.secret'
  create: true
  dotpath: home
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  d_config_aerc:
    src: config/aerc
    dst: ~/.config/aerc
    cmpignore:
    - accounts.conf
    instignore:
    - accounts.conf
    upignore:
    - accounts.conf
  f_config_alacritty: # TODO: Remove?
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  d_config_asdf:
    src: config/asdf
    dst: ~/.config/asdf
  f_config_dunst:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  d_config_git:
    src: config/git
    dst: ~/.config/git
  f_config_gtk3:
    dst: ~/.config/gtk-3.0/settings.ini
    src: config/gtk-3.0/settings.ini
  d_config_i3:
    dst: ~/.config/i3
    src: config/i3
  f_config_i3status-rs:
    dst: ~/.config/i3status-rs/status.toml
    src: config/i3status-rs/status.toml
  d_config_isync:
    src: config/isync
    dst: ~/.config/isync
    cmpignore: # TODO: Move gpg file to .local
    - '*.gpg'
    instignore:
    - '*.gpg'
    upignore:
    - '*.gpg'
  d_config_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_config_mako:
    dst: ~/.config/mako/config
    src: config/mako/config
  f_config_mimeapps:
    dst: ~/.config/mimeapps.list
    src: config/mimeapps.list
  d_config_msmtp:
    src: config/msmtp
    dst: ~/.config/msmtp
  d_config_mutt:
    dst: ~/.config/mutt
    src: config/mutt
    cmpignore:
    - '*/tmp'
    instignore:
    - '*/tmp'
    upignore:
    - '*/tmp'
  d_config_nvim:
    dst: ~/.config/nvim
    src: config/nvim
    actions:
    - vim-plug
    cmpignore:
    - '*/.netrwhist'
    - '**/spell'
    - plugin/packer_compiled.lua
    instignore:
    - '*/.netrwhist'
    - '**/spell'
    - plugin/packer_compiled.lua
    upignore:
    - '*/.netrwhist'
    - '**/spell'
    - plugin/packer_compiled.lua
  d_config_paru:
    src: config/paru
    dst: ~/.config/paru
  d_config_redshift:
    dst: ~/.config/redshift
    src: config/redshift
  f_conifg_rofi:
    dst: ~/.config/rofi/config
    src: config/rofi/config
  f_config_rofipass:
    dst: ~/.config/rofi-pass/config
    src: config/rofi-pass/config
  f_config_simplecal: # TODO: Remove?
    dst: ~/.config/gsimplecal/config
    src: config/gsimplecal/config
  f_config_starship:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_config_sway:
    dst: ~/.config/sway
    src: config/sway
  d_config_systemd: # TODO: Remove???
    dst: ~/.config/systemd/user
    src: config/systemd/user
  f_config_termite: # TODO: Remove?
    dst: ~/.config/termite/config
    src: config/termite/config
  f_config_topgrade:
    dst: ~/.config/topgrade.toml
    src: config/topgrade.toml
  f_wallpaper: # TODO: Move to Pictures/wallpaper
    dst: ~/.config/wallpaper/arch-linux-dark.png
    src: config/wallpaper/arch-linux-dark.png
  d_config_zsh:
    dst: ~/.config/zsh
    src: config/zsh
    cmpignore:
    - '*.zwc'
    instignore:
    - '*.zwc'
    upignore:
    - '*.zwc'
  f_config_zathura:
    dst: ~/.config/zathura/zathurarc
    src: config/zathura/zathurarc
  f_config_zsh_99-my-env.zsh:
    src: config/zsh/99-my-env.zsh
    dst: ~/.config/zsh/99-my-env.zsh
  d_local_share_fonts:
    dst: ~/.local/share/fonts
    src: local/share/fonts
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gtk2:
    dst: ~/.gtkrc-2.0
    src: gtkrc-2.0
  f_tmux:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xinit:
    dst: ~/.xinitrc
    src: xinitrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
profiles:
  Mail:
    dotfiles:
    - d_config_mutt
    - d_config_isync
    - d_config_msmtp
  Desktop:
    dotfiles:
    - d_local_share_fonts
    - d_config_kitty
    - d_config_redshift
    - f_gtk2
    - f_config_gtk3
    - f_config_mimeapps
    - f_wallpaper
    - f_config_zathura
  Sway:
    dotfiles:
    - d_config_sway
    - f_config_i3status-rs
    - f_config_mako
  Xorg:
    dotfiles:
    - d_config_i3
    - f_config_dunst
    - f_conifg_rofi
    - f_config_rofipass
    - f_xinit
  Terminal:
    dotfiles:
    - d_bin
    - d_config_asdf
    - d_config_git
    - d_config_nvim
    - d_config_zsh
    - f_gitconfig
    - f_gitignore
    - d_config_paru
    - f_config_starship
    - f_tmux
    - f_config_topgrade
    - f_zshenv
    - f_zshrc
  WSL:
    include:
    - Terminal

  desktop:
    include:
    - Desktop
    - Mail
    - Terminal
    - Xorg

  laptop:
    dotfiles:
    - f_config_zsh_99-my-env.zsh
    include:
    - Desktop
    - Sway
    - Terminal
