icons = "none"

[theme]
name = "plain"
[theme.overrides]
separator = "  |  "

[[block]]
block = "speedtest"
bytes = true

[[block]]
block = "net"
device = "wlp1s0"
# format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
ssid = true
signal_strength = true
ip = true
# graph_down = true
speed_up = false
interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MFg} GiB ({MUpi}%)"
format_swap = "{SUp}%"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"
# on_click = "st -e gotop"

[[block]]
block = "backlight"
device = "acpi_video0"

[[block]]
block = "sound"
on_click = "st -e alsamixer"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 30
format = "%V - %F %R "
