icons = "none"

[theme]
name = "plain"
[theme.overrides]
separator = "  |  "

[[block]]
block = "speedtest"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = "/"

[[block]]
block = "memory"
display_type = "memory"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "backlight"
device = "acpi_video0"

[[block]]
block = "sound"
on_click = "st -e alsamixer"

[[block]]
block = "battery"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 30
format = "%V - %F %R "
