# scripts from ~/bin
export PATH=$PATH:$HOME/bin

# Cargo env
export PATH=$PATH:$HOME/.cargo/bin

# Local bins (mostly python)
export PATH=$PATH:$HOME/.local/bin

# Dotnet
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$DOTNET_ROOT
export PATH=$PATH:$HOME/.dotnet/tools

# Znap
export ZNAP_HOME=$HOME/.local/share/znap
{%@@ if profile == "work" @@%}

umask 022
{%@@ endif @@%}
