# scripts from ~/bin
export PATH=$PATH:$HOME/bin

# Cargo env
export PATH=$PATH:$HOME/.cargo/bin

# Local bins (mostly python)
export PATH=$PATH:$HOME/.local/bin

# Znap
export ZNAP_HOME=$HOME/.local/share/znap
{%@@ if profile == "work" @@%}

umask 022
{%@@ endif @@%}
