pfetch

for file in $HOME/.config/zsh/*.zsh; do
    source "$file"
done

{%@@ if profile == "desktop" or profile == "laptop" @@%}
znap eval frum 'frum init'

{%@@ endif @@%}
znap eval starship 'starship init zsh --print-full-init'
znap prompt
