for file in $HOME/.config/zsh/*.zsh; do
    source "$file"
done

pfetch

znap eval starship 'starship init zsh --print-full-init'
znap prompt

if [[ $- =~ i ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_TTY" ]]; then
    tmux attach -t ssh_tmux || tmux new-session -s ssh_tmux
fi
