#!/bin/sh
lock() {
	# Take screenshot
	scrot /tmp/screen_locked.png
	# Pixellate it 10x
	mogrify -scale 5% -scale 2000% /tmp/screen_locked.png
	# Lock screen
	i3lock -i /tmp/screen_locked.png
	# Turn the screen off after a delay
	if [[ $1 = "lock" ]]; then
		sleep 60; pgrep i3lock && xset dpms force off
	fi
}

case "$1" in
	lock)
		lock $1
		;;
	logout)
		i3-msg exit
		;;
	suspend)
		lock && systemctl suspend
		;;
	hibernate)
		lock && systemctl hibernate
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
		exit 2
esac

exit 0
