#!/usr/bin/env sh
# vim: ft=sh

SUDO=/usr/bin/sudo
SYSCTL=/usr/bin/systemctl

echo "Enabling services..."

USER_SERVICES=(
    "keybase"
    "dunst"
    "geoclue-agent"
    "redshift"
)
USER_TIMERS=(
    "low-battery"
    "update-alert"
)
SYSTEM_SERVICES=(
    "acpid"
    "tlp"
    "tlp-sleep"
)

for SERVICE in ${USER_SERVICES[@]} ; do
    if ! $SYSCTL --user is-enabled $SERVICE.service > /dev/null ; then
        echo "Enable $SERVICE on login"
        $SYSCTL --user enable $SERVICE.service
    fi
done

for TIMER in ${USER_TIMERS[@]} ; do
    if ! $SYSCTL --user is-enabled $TIMER.timer > /dev/null ; then
        echo "Enable $TIMER on login"
        $SYSCTL --user enable $TIMER.timer
    fi
done

for SERVICE in ${SYSTEM_SERVICES[@]} ; do
    if ! $SYSCTL is-enabled $SERVICE.service > /dev/null ; then
        echo "Enable $SERVICE on login"
        $SUDO $SYSCTL enable $SERVICE.service
    fi
done

echo "Done"
