#!/usr/bin/env sh
# vim: ft=sh

# Install rustup if not installed
if [[ ! -x $(command -v rustup) ]]; then
    sudo pacman -S rustup
fi

# Install toolchains
rustup toolchain add stable
rustup default stable
rustup toolchain add nightly

# Install components
rustup component add rls-preview rust-analysis rust-src rustfmt-preview

# Install bat
if [[ ! -x $(command -v bat) ]]; then
    cargo install bat
fi

# Install cargo-update
# if [[ ! -x $(cargo-install-update) ]]; then
#     cargo install cargo-update
# fi

# Install racer
if [[ ! -x $(command -v cargo) ]]; then
    # Install racer dependencies
    sudo pacman -S base-devel cmake zlib openssl --needed

    cargo +nightly install racer
fi

# Install alacritty
if [[ ! -x $(command -v alacritty) ]]; then
    # Install dependencies
    # sudo pacman -S cmake freetype2 fontconfig pkg-config make xclip --needed

    yay -S alacritty-git
fi

# Install fd and ripgrep
sudo pacman -S fd ripgrep --needed
