#!/usr/bin/env sh
# vim: ft=sh

GIT=/usr/bin/git
MAKEPKG=/usr/bin/makepkg
PACAUR=/usr/bin/yay
PACMAN=/usr/bin/pacman
SUDO=/usr/bin/sudo

# Get the passwd for sudo
$SUDO -v

# Keep sudo alive through the hole script
while true; do $SUDO -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

PACK_GROUPS=(
    "base-devel"
    "texlive-most"
)

PACKAGES=(
    "acpi"
    "alsa-tools"
    "alsa-utils"
    "arandr"
    "bind-tools"
    "chromium"
    "cmake"
    "compton"
    "diff-so-fancy"
    "dunst"
    "exfat-utils"
    "f2fs-tools"
    "fd"
    "feh"
    "firefox"
    "fontconfig"
    "freetype2"
    "fzf"
    "ghostscript"
    "gdisk"
    "gimp"
    "gnome-keyring"
    "gsimplecal"
    "gtk2"
    "gtk3"
    "htop"
    "hugo"
    "imagemagick"
    "keybase"
    "keybase-gui"
    "linux-headers"
    "linux-lts"
    "make"
    "mpv"
    "mtpfs"
    "neomutt"
    "neovim"
    "ntfs-3g"
    "openssh"
    "openssl"
    "p7zip"
    "pacman-contrib"
    "pass"
    "pass-otp"
    "pavucontrol"
    "perl-file-mimeinfo"
    "pkg-config"
    "playerctl"
    "ponymix"
    "pulseaudio"
    "pulseaudio-alsa"
    "python"
    "python-neovim"
    "python-unidecode"
    "python2"
    "python2-neovim"
    "qt4"
    "r"
    "ranger"
    "redshift"
    "reflector"
    "ripgrep"
    "rsync"
    "rustup"
    "scrot"
    "thunderbird"
    "tlp"
    "tmux"
    "vlc"
    "w3m"
    "xclip"
    "zathura"
    "zathura-pdf-poppler"
    "zlib"
)

AURPACKAGES=(
    "checkupdates+aur"
    "gitflow-avh"
    "gitflow-zshcompletion-avh"
    "gtk-theme-united-gnome"
    "jabref"
    "jdk"
    "nerd-fonts-complete"
    "nextcloud-client"
    "polybar"
    "rofi-pass"
    "spotify"
    "standardnotes-desktop"
    "teamviewer"
    "wpa-cute"
)

echo -e "\nInstalling packages from groups..."
for GROUP in ${PACK_GROUPS[@]} ; do
    PACKS=$($PACMAN -Sg $GROUP | awk -F ' ' '{print $2}')
    for PACK in ${PACKS[@]} ; do
        if ! $PACMAN -Q $PACK > /dev/null ; then
            echo -e "\nInstalling package: '$PACK'..."
            $SUDO $PACMAN -S $PACK --needed --noconfirm
            echo -e "Package successfully installed: '$PACK'\n"
        fi
    done
done

echo -e "\nInstalling packages from official repo..."
for PACK in ${PACKAGES[@]} ; do
    if ! $PACMAN -Q $PACK > /dev/null ; then
        echo -e "\nInstalling package: '$PACK'..."
        $SUDO $PACMAN -S $PACK --needed --noconfirm
        echo -e "Package successfully installed: '$PACK'\n"
    fi
done

echo -e "\nInstalling packages from AUR"
if ! $PACMAN -Q yay-bin > /dev/null ; then
    echo -e "\nInstalling AUR helper 'yay'..."
    dir=$(pwd)
    cd $(mktemp -d)
    $GIT clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    $MAKEPKG -si
    cd ..
    rm -rf yay-bin
    cd $dir
    echo -e "AUR Helper 'yay' successfully installed\n"
fi

for PACK in ${AURPACKAGES[@]}; do
    if ! $PACMAN -Qs $PACK > /dev/null ; then
        echo -e "\nInstalling package: '$PACK'..."
        $PACAUR -S $PACK --needed --noconfirm
        echo -e "Package successfully installed: '$PACK'\n"
    fi
done

echo -e "\nAll packages were installed\n"
