"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"

[directory]
truncation_length = 3
truncation_symbol = "…/"

[python]
symbol = " "

[ruby]
symbol = " "

[sudo]
disabled = false
