#!/usr/bin/env sh
# vim: ft=sh

# Install rustup if not installed
if [[ ! -x $(command -v rustup) ]]; then
    sudo pacman -S rustup
fi

# Install toolchains
rustup toolchain add stable
rustup default stable
rustup toolchain add nightly

# Install components
rustup component add rls-preview rust-analysis rust-src rustfmt-preview

# Install bat
if [[ ! -x $(command -v bat) ]]; then
    cargo install bat
fi

# Install cargo-update
if ! cargo install-update --version > /dev/null ; then
    cargo install cargo-update
fi

# Install racer
if [[ ! -x $(command -v cargo) ]]; then
    cargo +nightly install racer
fi

# Install alacritty
if [[ ! -x $(command -v alacritty) ]]; then
    yay -S alacritty-git
fi
