#!/usr/bin/env sh
# vim: ft=sh

# Install rustup if not installed
if [[ ! -x $(command -v rustup) ]]; then
    sudo pacman -S rustup
fi

# Install toolchains
rustup toolchain add stable
rustup default stable
rustup toolchain add nightly

# Install components
rustup component add rls rust-analysis rust-src rustfmt clippy

# Install cargo-update
if ! cargo install-update --version > /dev/null ; then
    cargo install cargo-update
fi

# Install racer
if [[ ! -x $(command -v cargo) ]]; then
    cargo +nightly install racer
fi

