theme = "plain"
icons = "none"

[[block]]
block = "net"
device = "wlp1s0"
ssid = true
ip = true
interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GiB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MFg} GiB"
format_swap = "{SUp}%"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
format = "{percentage}% {time} {power} W"

[[block]]
block = "time"
interval = 30
format = "%V - %d.%m.%Y %R"
