#!/bin/sh
lock() {
    local image=/tmp/screen_locked.png
    # Remove old screenshot
    if [[ -f $image ]]; then
        rm $image
    fi
    # Take new screenshot
    scrot $image
    # Pixellate it 10x
    mogrify -scale 5% -scale 2000% $image
    # Lock screen
    i3lock -i $image
}

case "$1" in
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        lock
esac

exit 0
