icons = "none"

[theme]
name = "plain"
[theme.overrides]
separator = "  |  "

[[block]]
block = "net"
device = "enp5s0"
format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"
interval = 2

[[block]]
block = "nvidia_gpu"

[[block]]
block = "disk_space"
format = "{icon} {used}/{total} ({available} free)"

[[block]]
block = "memory"
format_mem = "{mem_used} ({mem_used_percents})"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
format = "{barchart} {utilization} {frequency}"
on_click = "st -e btm"

[[block]]
block = "sound"
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
interval = 30
format = "%V - %F %R "
