[theme]
theme = "plain"
[theme.overrides]
separator = "  |  "

[[block]]
block = "net"
device = "enp5s0"
format = "$icon {$ssid $signal_strength|Wired} {$ip} {$speed_down.eng(prefix:K)} {$graph_down}"
interval = 2

[[block]]
block = "nvidia_gpu"

[[block]]
block = "disk_space"
format = "{$icon} {$used}/{$total} ({$available} free)"

[[block]]
block = "memory"
format = "$icon {$mem_used} ({$mem_used_percents})"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
format = "$icon {$barchart} {$utilization} {$frequency}"
[[block.click]]
button = "left"
cmd = "st -e btm"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime(f:'%V - %F %R') "
