#!/usr/bin/env sh

# System Update

# --------------------------- #
# Snapshot - Rollback - Btrfs #
# --------------------------- #

MV=/usr/bin/mv
BTRFS=/usr/bin/btrfs
SED=/usr/bin/sed
PACMAN=/usr/bin/pacman
PACAUR=/usr/bin/yay
CP=/usr/bin/cp
REFLECTOR=/usr/bin/reflector
SUDO=/usr/bin/sudo
CHUP=/usr/bin/checkupdates+aur
# --------------------------- #
#       Check Updates         #
# --------------------------- #

echo -e "Checking for updates...\n"
$CHUP
read -n 1 -p "Do you want to perform a system update [y/N]? " INPUT
if [[ ! "$INPUT" =~ [yY] ]]; then
    echo -e "\nProgram finished"
    exit 0
fi
echo -e "\n"

# --------------------------- #
#      Snapshot System        #
# --------------------------- #

# -------- OLDSTABLE -------- #

$SUDO $BTRFS subvolume delete /.snapshots/OLDSTABLE
$SUDO $MV /.snapshots/STABLE /.snapshots/OLDSTABLE
$SUDO $SED -i 's/STABLE/OLDSTABLE/g' /.snapshots/OLDSTABLE/etc/fstab
$SUDO $CP /boot/vmlinuz-linux-stable /boot/vmlinuz-linux-oldstable
$SUDO $CP /boot/initramfs-linux-stable.img /boot/initramfs-linux-oldstable.img

# --------- STABLE ---------- #

$SUDO $BTRFS subvolume snapshot / /.snapshots/STABLE
$SUDO $SED -i 's/TESTING/STABLE/g' /.snapshots/STABLE/etc/fstab
$SUDO $CP /boot/vmlinuz-linux-lts /boot/vmlinuz-linux-stable
$SUDO $CP /boot/initramfs-linux-lts.img /boot/initramfs-linux-stable.img

# --------------------------- #
#       Update System         #
# --------------------------- #

$SUDO $REFLECTOR --verbose -l 5 -p https --sort rate --save /etc/pacman.d/mirrorlist
$PACAUR -Syyu

# --------------------------- #
#     Balance Filesystem      #
# --------------------------- #

$SUDO $BTRFS balance start -dusage=5 /btrfs

# --------------------------- #
#       Update Misc           #
# --------------------------- #

rustup update stable
cargo install-update -a
nvim +PlugUpdate +qall

# vim: ft=sh
